;====================================================================
; Main.asm file generated by New Project wizard
;
; Created: Thu May 2 2024
; Processor: 8086
; Compiler: MASM32
;
; Before starting simulation set Internal Memory Size 
; in the 8086 model properties to 0x10000
;====================================================================
; SUBJECT: MICROPROCESSOR LAB
; EXP. NO.: 12
; APL 12: Interfacing Seven Segment Display and Program
; NAME: Aniket More
; DIVISION: S2
; ROLL NO.: 81
; DATE: 02/05/2024

DATA_SEG SEGMENT
    DISP DB 3FH,06H,5BH,4FH,66H,6DH,7DH,07H,7FH,6FH
    COUNT DW 0AH
    CNT DW 0FFFFH
DATA_SEG ENDS

CODE SEGMENT PUBLIC 'CODE'
    ASSUME CS:CODE, DS:DATA_SEG

START:
    ; initialise the data segment
    MOV AX, DATA_SEG
    MOV DS, AX
    MOV AL, 80H ; control word for port A output
    MOV DX, 06H ; ADDRESS OF CONTROL REGISTER
    OUT DX, AL ; write control word to control register
    MOV DI, OFFSET DISP ; initialize the pointer
    MOV DX, 00H ; address of the port A

AGAIN: 
    MOV AL, [DI] ; read the display code
    INC DI
    OUT DX, AL ; send code to port A

    MOV DX, CNT

DELAY: 
    DEC DX
    JNZ DELAY
    DEC COUNT
    JNZ AGAIN

ENDLESS:
    JMP ENDLESS

CODE ENDS
END START
